version: '3'
services:
  arangodb:
    container_name: arangodb
    image: arangodb:latest
    restart: always
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: thisisyourrootpassword
    volumes:
      - $PWD/arangodb_data:/var/lib/arangodb3
      - $PWD/geojson:/geo
